baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kebabsec"
theme = "hello-friend-ng"

[params]
	dateform = "Jan 2, 2006"
	dateformShort = "Jan 2"
	dateformNum = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04"
	homeSubtitle = "bug squashing squad living on chain ğŸğŸ¯"
  enableThemeToggle = true
  enableSharingButtons = true
  enableGlobalLanguageMenu = false

  [params.portrait]
    path     = "/logo.svg"
    alt      = "Portrait"
    maxWidth = "140px"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/kebabsec"

  [[params.social]]
    name = "github"
    url = ""

  [[params.social]]
    name = "telegram"
    url = ""

  [[params.social]]
    name = "email"
    url = ""

  [[params.social]]
    name = "discord"
    url = ""

[[menu.main]]
  identifier = "audit"
  name       = "Audits"
  url        = "/audit"

[[menu.main]]
  identifier = "post"
  name       = "Posts"
  url        = "/post"

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

[taxonomies]
 	category = "blog"
 	tag = "tags"
 	series = "series"

[author]
  name = "Kebabsec"

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []
  bottomText = []

[languages]
	[languages.en]
    title = "Kebabsec"
    subtitle = "bug squashing squad living on chain ğŸğŸ¯"
    keywords = "Solidity, audit, security, DeFi"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "kebabsec"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

