baseURL = "https://kebabsec.xyz/"
languageCode = "en-us"
title = "Kebabsec"
theme = "hello-friend-ng"

paginate = 99
rssLimit  = 99

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

[params]
	dateform = "Jan 2, 2006"
	dateformShort = "Jan 2"
	dateformNum = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04"
	homeSubtitle = "bug squashing squad living on chain ğŸğŸ¯"
  enableThemeToggle = true
  enableSharingButtons = true
  enableGlobalLanguageMenu = false

  [params.portrait]
    path     = "/logo.jpg"
    alt      = "Portrait"
    maxWidth = "140px"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/kebabsec"

  [[params.social]]
    name = "github"
    url = "https://github.com/kebabsec"

  [[params.social]]
    name = "email"
    url = "mailto:kebabsecbusiness@gmail.com"

  [[params.social]]
    name = "telegram"
    url = "https://t.me/kebabsec"

  [[params.social]]
    name = "discord"
    url = "https://discord.com/users/303927813285609482"

[[menu.main]]
  identifier = "audits"
  name       = "Audits"
  url        = "/audits"

[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts"

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

[taxonomies]
 	category = "blog"
 	tag = "tags"
 	series = "series"

[author]
  name = "Kebabsec"

[params.footer]
  trademark = true
  rss = false
  copyright = true
  author = true

  topText = []
  bottomText = [
    "Audit report rights are reserved by the respective commissioning parties.",
  ]

[languages]
	[languages.en]
    title = "Kebabsec"
    subtitle = "bug squashing squad living on chain ğŸğŸ¯"
    keywords = "Solidity, audit, security, DeFi"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/kebabsec"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
